<?php

declare(strict_types=1);

namespace App\Module\Front\Plugin;

use Air\Core\Plugin;
use Air\Core\Request;
use Air\Core\Response;
use Air\Core\Router;

class FrontModulePlugin extends Plugin
{
  /**
   * @param Request $request
   * @param Response $response
   * @param Router $router
   * @return void
   */
  public function postRun(Request $request, Response $response, Router $router): void
  {
    parent::postRun($request, $response, $router);

    // TODO: Change the autogenerated stub
    // This plugin will works only within Front module
  }

  /**
   * @param Request $request
   * @param Response $response
   * @param Router $router
   * @return void
   */
  public function preRun(Request $request, Response $response, Router $router)
  {
    parent::preRun($request, $response, $router);

    // TODO: Change the autogenerated stub
    // This plugin will works only within Front module
  }
}