<!doctype html>
<html lang="en" class="h-100 w-100">
<head>
  <meta charset="UTF-8">

  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <title>AirCms</title>

  <?php echo $this->asset([
    'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap',
    'air/vendor/mdb/light.css',
  ]); ?>

</head>
<body data-mdb-theme="dark" class="h-100 w-100">

<div class="h-100 w-100 d-flex flex-column">

  <div class="card m-3" style="height: 200px;">
    <div class="card-body">
      <h1>Welcome to <b><?php echo $this->title; ?></b></h1>
    </div>
  </div>

  <div class="mx-3 flex-grow-1 d-flex">

    <div class="card me-3" style="width: 300px;">
      <div class="card-body">
        Aside
      </div>
    </div>

    <div class="card flex-grow-1">
      <div class="card-body">
        <?php echo $this->getContent(); ?>
      </div>
    </div>
  </div>

  <div class="card m-3">
    <div class="card-body">
      Footer
    </div>
  </div>

</div>

</body>
</html>