<?php

namespace App\Plugin;

use Air\Core\Plugin;
use Air\Core\Request;
use Air\Core\Response;
use Air\Core\Router;

class AllModulesPlugin extends Plugin
{
  /**
   * @param Request $request
   * @param Response $response
   * @param Router $router
   * @return void
   */
  public function postRun(Request $request, Response $response, Router $router): void
  {
    parent::postRun($request, $response, $router);

    // TODO: Change the autogenerated stub
    // This plugin will works for all modules
  }

  /**
   * @param Request $request
   * @param Response $response
   * @param Router $router
   * @return void
   */
  public function preRun(Request $request, Response $response, Router $router)
  {
    parent::preRun($request, $response, $router);

    // TODO: Change the autogenerated stub
    // This plugin will works for all modules
  }
}